# Generated by Django 5.2.8 on 2025-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_es', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('desc_es', models.TextField()),
                ('desc_en', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('trekking', 'Trekking'), ('mtb', 'Mountain Bike'), ('special', 'Eventos especiales')], max_length=20)),
                ('duration', models.CharField(max_length=120)),
                ('difficulty', models.CharField(max_length=120)),
                ('season', models.CharField(max_length=120)),
                ('external_url', models.URLField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['category', 'title_es'],
            },
        ),
    ]
