# Generated by Django 5.2.8 on 2025-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_es', models.CharField(max_length=140)),
                ('name_en', models.CharField(blank=True, max_length=140)),
                ('desc_es', models.TextField()),
                ('desc_en', models.TextField(blank=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('price_from_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name_es'],
            },
        ),
    ]
