# Generated by Django 5.2.8 on 2025-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('whatsapp_url', models.URLField(help_text='Enlace completo a WhatsApp API')),
                ('instagram_url', models.URLField()),
                ('maps_url', models.URLField()),
                ('address_es', models.CharField(max_length=255)),
                ('address_en', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
