# Generated by Django 5.2.8 on 2025-11-07 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('desc_es', models.TextField(blank=True)),
                ('desc_en', models.TextField(blank=True)),
                ('price_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diet_flags', models.JSONField(blank=True, default=list, help_text="Arreglo de etiquetas como ['vegan','gluten-free']")),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menusection')),
            ],
            options={
                'ordering': ['section', 'name_es'],
            },
        ),
    ]
